- Dockerfile
- heroku.yml
- package-lock.json
- package.json
- server.js
This is to mirror the currently deployed version before I finish redirecting the url to the new infrastructure.
> Add Docker for Heroku and bump security versions

- views/partials/doc-content.ejs
> Update Base URL

- .eslintrc.json
- .travis.yml
- js/code.js
- models/feature.js
- package-lock.json
- package.json
- routes/ability-scores.js
- routes/classes.js
- routes/conditions.js
- routes/damage-types.js
- routes/equipment-categories.js
- routes/equipment.js
- routes/features.js
- routes/languages.js
- routes/magic-schools.js
- routes/monsters.js
- routes/proficiencies.js
- routes/races.js
- routes/skills.js
- routes/spellcasting.js
- routes/spells.js
- routes/startingequipment.js
- routes/subclasses.js
- routes/subraces.js
- routes/traits.js
- routes/utility.js
- routes/weapon-properties.js
- server.js
- views/pages/docs.ejs
This address #21 and #24.
* `/api` now returns something again
* All files have been linted
* Adds in Travis CI
> Add Travis CI, Linting, and fix /api route

- js/code.js
- views/partials/main.ejs
- views/partials/navbar.ejs
With the index changes, I needed to at least update the homepage to match. Doc updates will come in a separate PR.
* Updates homepage to use string indices instead of numbers
* Fixed Chat link to point to discord
* Updated Changelog
* Added Contribute link
> Fix up Homepage

- views/partials/footer.ejs
I'm no longer the owner of the api and database
> removing name

- server.js
Enabled preflight for cors requests, as requested to https://github.com/adrpadua/5e-srd-api/issues/9.
> enable cors in preflight

- routes/races.js
- routes/subraces.js
- routes/utility.js
Looks like a few of  the races endpoints weren't working because they couldn't find a race. I've updated the utility and had it search by index instead.
> Fix race and subrace routes

- views/partials/doc-content.ejs
- views/partials/doc-resource-ability-scores.ejs
- views/partials/doc-resource-classes.ejs
- views/partials/doc-resource-common-models.ejs
- views/partials/doc-resource-conditions.ejs
- views/partials/doc-resource-damage-types.ejs
- views/partials/doc-resource-equipment.ejs
- views/partials/doc-resource-features.ejs
- views/partials/doc-resource-languages.ejs
- views/partials/doc-resource-levels.ejs
- views/partials/doc-resource-lists.ejs
- views/partials/doc-resource-magic-schools.ejs
- views/partials/doc-resource-proficiencies.ejs
- views/partials/doc-resource-races.ejs
- views/partials/doc-resource-skills.ejs
- views/partials/doc-resource-subclasses.ejs
- views/partials/doc-resource-subraces.ejs
This partially address #1.
This is a small update to docs to at least have them show the new index type. There is a lot of work that still needs to be done to get everything reflected, but this is a start.
> Small documentation update

- routes/ability-scores.js
- routes/classes.js
- routes/conditions.js
- routes/damage-types.js
- routes/equipment-categories.js
- routes/equipment.js
- routes/features.js
- routes/languages.js
- routes/magic-schools.js
- routes/monsters.js
- routes/proficiencies.js
- routes/races.js
- routes/skills.js
- routes/spellcasting.js
- routes/spells.js
- routes/startingequipment.js
- routes/subclasses.js
- routes/subraces.js
- routes/traits.js
- routes/weapon-properties.js
- server.js
This address part of #34 
Looks like some routes would just timeout instead of 404ing. Also some routes would give back `null` instead of 404ing.
This will also 500 on internal errors.
> Add in 404 error support

- README.md
> Add Heroku badge

- CHANGELOG.md
- README.md
- docker-compose.yml
This sets up `docker-compose.yml`. This will be nice for running tests because we'll have the database. It also simplifies running things locally.
> Add docker-compose.yml

- views/partials/navbar.ejs
The Home link doesn't work if you're on the docs. Now it does.
> Bug: Fix the home link

- src/server.js
This is based on Trapjaw's suggestion on the Discord
> Update CORS settings based on Trapjaw's suggestion

- docker-compose.yml
Fix for #51 
I don't know how I introduced this or how it was working before but this should fix it.
> Fix for Docker Compose

- src/views/pages/docs.ejs
- src/views/pages/index.ejs
- src/views/partials/doc-content.ejs
- src/views/partials/doc-left-col.ejs
- src/views/partials/doc-resource-ability-scores.ejs
- src/views/partials/doc-resource-classes.ejs
- src/views/partials/doc-resource-common-models.ejs
- src/views/partials/doc-resource-conditions.ejs
- src/views/partials/doc-resource-damage-types.ejs
- src/views/partials/doc-resource-equipment.ejs
- src/views/partials/doc-resource-features.ejs
- src/views/partials/doc-resource-lists.ejs
- src/views/partials/doc-resource-magic-schools.ejs
- src/views/partials/doc-resource-races.ejs
- src/views/partials/doc-resource-skills.ejs
- src/views/partials/footer.ejs
- src/views/partials/head.ejs
- src/views/partials/main.ejs
This just cleans up EJS auto formatting.
> Cleaning up any EJS auto-formatting

- package-lock.json
- package.json
Addressing the security vulnerabilities
> Security Vulnerability Review

- src/views/partials/doc-resource-ability-scores.ejs
- src/views/partials/doc-resource-classes.ejs
- src/views/partials/doc-resource-skills.ejs
Removes a couple of small tag fragments that had snuck into the documentation. Apologies for the minor PR.
> Tiny documentation tweaks

- README.md
- src/views/partials/doc-content.ejs
- src/views/partials/main.ejs
Fixes some confusing URLs
CI and eyeballs
None
> Fixing urls

- src/controllers/api/spellcastingController.js
- src/models/spellcasting.js
- src/tests/controllers/api/spellcastingController.test.js
Fixes the spellcasting endpoint to actually work. My bad.
CI
This fixes #70
> Fixing spellcasting endpoint

- .gitignore
- package-lock.json
- package.json
This ignores .idea files, which are generated by JetBrains IDEs, so that they are not accidentally committed. It also moves a dependency into dev dependencies.
The tests are still passing.
No.
> Minor quality of life improvements

- src/views/partials/doc-resource-ability-scores.ejs
- src/views/partials/doc-resource-classes.ejs
- src/views/partials/doc-resource-conditions.ejs
- src/views/partials/doc-resource-damage-types.ejs
- src/views/partials/doc-resource-equipment.ejs
the documentation has been updated
nope
issue #57
> updated doc-resource-classes.ejs

- src/views/partials/doc-resource-monsters.ejs
Fixes a spelling mistake from a [previous pull request.](https://github.com/bagelbits/5e-srd-api/pull/90)
Manually
Yes #64 (again)
> Fixed spelling mistake in documentation

- src/views/partials/doc-resource-monsters.ejs
- src/views/partials/doc-resource-traits.ejs
This updates some docs that got missed, as well as changes in https://github.com/bagelbits/5e-database/pull/278
CI, but also, it's just docs.
No
> Update docs to match reality.

- docker-compose.yml
- src/controllers/api/magicItemController.js
- src/models/magicItem.js
- src/routes/api.js
- src/routes/api/magicItems.js
- src/tests/controllers/api/magicItemController.test.js
- src/tests/integration/server.itest.js
- src/views/partials/doc-content.ejs
- src/views/partials/doc-left-col.ejs
- src/views/partials/doc-resource-equipment-categories.ejs
- src/views/partials/doc-resource-magic-items.ejs
This exposes the Magic Items that have been added to the database. Also adds the documentation.
CI!
https://github.com/bagelbits/5e-database/issues/115
> Expose Magic Items

- src/controllers/api/spellController.js
- src/models/spell.js
- src/tests/integration/server.itest.js
- src/views/partials/doc-resource-spells.ejs
Adds spell school query param
CI
Part of #105
> Add spell school

- .travis.yml
Deploys to heroku via travis using encrypted key.
We're doing it live! :D
This resolves #101
> Deploy to Heroku via Travis

- .travis.yml
This makes it so it doesn't deploy after every job finishes.
Research.
No
> Let's do this correctly

- src/tests/controllers/api/magicItemController.test.js
- src/tests/controllers/api/monsterController.test.js
- src/tests/controllers/api/spellController.test.js
- src/tests/integration/server.itest.js
- src/util/RedisClient.js
- src/util/environmentVariables.js
- src/util/index.js
> Simplify redis logic and organize utils

- src/views/partials/doc-resource-magic-items.ejs
Adds index field to the magic item example json
lgtm
> Adds index field to magic item example

- src/controllers/api/utility.js
Fixes `TypeError · string.replace is not a function`
CI
No. Just a Bugsnag error.
> Fix TypeError

- src/controllers/api/ruleController.js
- src/controllers/api/ruleSectionController.js
- src/tests/integration/server.itest.js
Cleanups up some issues with the integration tests and gets it ready for break up
CI
No
> Some clean up

- src/views/partials/doc-resource-equipment.ejs
- src/views/partials/doc-resource-languages.ejs
- src/views/partials/doc-resource-subraces.ejs
- Rename some data types from `map` to `object`
- Rename one data type from `array` to `list`
- localhost
- no
> ecs: small documentation improvements (3)

- src/start.js
Converts from chained promises to await notation for `start.js`
CI
Technically, this is related to #131
> Switch to await style notation for start.js

- src/controllers/api/classController.js
- src/controllers/api/magicItemController.js
- src/controllers/api/monsterController.js
- src/controllers/api/raceController.js
- src/controllers/api/ruleController.js
- src/controllers/api/ruleSectionController.js
- src/controllers/api/spellController.js
- src/controllers/api/spellcastingController.js
- src/controllers/api/startingEquipmentController.js
- src/controllers/api/subclassController.js
- src/controllers/api/subraceController.js
- src/controllers/simpleController.js
This drops the majority of the async/await in favor of promise chains.
CI
This resolves #131
> Drop await where it makes sense

- src/views/partials/doc-content.ejs
- src/views/partials/doc-left-col.ejs
Adds GraphQL docs
Local `npm start`
No
> Add GraphQL docs

- src/controllers/api/classController.js
- src/controllers/api/magicItemController.js
- src/controllers/api/monsterController.js
- src/controllers/api/raceController.js
- src/controllers/api/ruleController.js
- src/controllers/api/ruleSectionController.js
- src/controllers/api/spellController.js
- src/controllers/api/subclassController.js
- src/controllers/api/subraceController.js
- src/controllers/api/utility.js
- src/controllers/simpleController.js
- src/tests/controllers/api/utility.test.js
Adds a `select` to our queries so we're only getting the data we need from the DB.
CI and local testing.
This resolves #148
> Replace NamedAPIResource with ResourceList

- src/controllers/api/classController.js
- src/controllers/api/magicItemController.js
- src/controllers/api/monsterController.js
- src/controllers/api/raceController.js
- src/controllers/api/ruleController.js
- src/controllers/api/ruleSectionController.js
- src/controllers/api/spellController.js
- src/controllers/api/startingEquipmentController.js
- src/controllers/api/subclassController.js
- src/controllers/api/subraceController.js
- src/controllers/simpleController.js
- src/start.js
- src/tests/util/data.test.js
- src/util/data.js
- src/util/index.js
- src/util/prewarmCache.js
- src/util/regex.js
This adds prewarming to the main indices that are currently cached. This also refactors the utility file into util and brakes it up.
I tested this locally by comparing return times between prewarmed and not prewarmed. And even locally, it sped things up by a factor of 5.
Also, CI
This resolves #91
> Prewarm cache

- src/views/partials/doc-resource-weapon-properties.ejs
- correct the type for the index field
- fix the id tag so clicking from the sidebar works
- localhost
- no
> ecs: fix weapon-properties documentation

- src/models/monster.js
Expands the mongoose schema for monster fields
locally
#153
> Monster Mongoose Schema Update :dragon:

- src/graphql/equipment.js
- src/views/partials/doc-resource-equipment.ejs
Updates docs to show two_handed_damage
Also updates GraphQL
CI
No
> Switch to two_handed_damage

- src/models/spell.js
This addresses part of #172 
Locally
#172
> Adds in slot_level fields for spells

- src/models/abilityScore.js
- src/models/class.js
- src/models/common.js
- src/models/equipment.js
- src/models/equipmentCategory.js
- src/models/feature.js
- src/models/level.js
- src/models/magicItem.js
- src/models/monster.js
- src/models/proficiency.js
- src/models/race.js
- src/models/rule.js
- src/models/skill.js
- src/models/spell.js
- src/models/startingEquipment.js
- src/models/subclass.js
- src/models/subrace.js
- src/models/trait.js
Consolidates our use of NamedAPIResource
CI
This resolves #172
> Consolidate Common Mongoose Patterns

- src/models/monster.js
- src/views/partials/doc-resource-monsters.ejs
This matches the changes in https://github.com/bagelbits/5e-database/pull/331
CI
https://github.com/bagelbits/5e-database/issues/304
> Split all the lycanthropes

- docker-compose.yml
Switches to similar user for dockerhub.
CI
No
> Switch to new image

- src/controllers/api/classController.js
- src/models/class.js
- src/tests/controllers/api/classController.test.js
- src/views/partials/doc-resource-classes.ejs
Exposes starting equipment that is being merged into class in [this PR.](https://github.com/5e-bits/5e-database/pull/343/files)
CI
This is part of https://github.com/5e-bits/5e-database/issues/251
> Merge starting equipment into class

- package-lock.json
Reverts 5e-bits/5e-srd-api#204
> Revert "Bump ua-parser-js from 0.7.23 to 0.7.28"

- docker-compose.yml
Updates docker-compose to use the current redis version
CI
No. But it is vaguely related to #213
> Updating redis image to match reality

- package-lock.json
- src/tests/controllers/api/abilityScoreController.test.js
- src/tests/controllers/api/classController.test.js
- src/tests/controllers/api/conditionController.test.js
- src/tests/controllers/api/damageTypeController.test.js
- src/tests/controllers/api/equipmentCategoryController.test.js
- src/tests/controllers/api/equipmentController.test.js
- src/tests/controllers/api/featureController.test.js
- src/tests/controllers/api/languageController.test.js
- src/tests/controllers/api/magicItemController.test.js
- src/tests/controllers/api/magicSchoolController.test.js
- src/tests/controllers/api/monsterController.test.js
- src/tests/controllers/api/proficiencyController.test.js
- src/tests/controllers/api/raceController.test.js
- src/tests/controllers/api/ruleSectionController.test.js
- src/tests/controllers/api/rulesController.test.js
- src/tests/controllers/api/skillController.test.js
- src/tests/controllers/api/spellController.test.js
- src/tests/controllers/api/startingEquipmentController.test.js
- src/tests/controllers/api/subclassController.test.js
- src/tests/controllers/api/subraceController.test.js
- src/tests/controllers/api/traitController.test.js
- src/tests/controllers/api/weaponPropertyController.test.js
- src/tests/controllers/simpleController.test.js
runs 'npm update" to handle some security updates
CI
Various security issues
> npm update

- package-lock.json
- package.json
- src/graphql/schema.js
- src/models/abilityScore.js
- src/models/alignment.js
- src/models/background.js
- src/models/class.js
- src/models/common.js
- src/models/condition.js
- src/models/damageType.js
- src/models/equipment.js
- src/models/equipmentCategory.js
- src/models/feature.js
- src/models/language.js
- src/models/level.js
- src/models/magicItem.js
- src/models/magicSchool.js
- src/models/monster.js
- src/models/proficiency.js
- src/models/race.js
- src/models/rule.js
- src/models/ruleSection.js
- src/models/skill.js
- src/models/startingEquipment.js
- src/models/subclass.js
- src/models/subrace.js
- src/models/trait.js
- src/models/weaponProperty.js
This properly allows sorting and filtering on all primitive fields in GraphQL. This, unfortunately, means I needed to index everything.
CI and local testing
No but it was raised in #general.
> Fix filter and sort for GraphQL

- src/views/partials/doc-resource-backgrounds.ejs
- src/views/partials/doc-resource-races.ejs
- src/views/partials/doc-resource-subclasses.ejs
- src/views/partials/doc-resource-subraces.ejs
Fixes the noted attribute type and descriptions of various attributes. Also adds several attributes where they were missing.
Wasn't.
No.
> Documentation Cleanup

- src/models/feature.js
- src/models/race.js
- src/models/subrace.js
- src/models/trait.js
- src/views/partials/doc-resource-features.ejs
- src/views/partials/doc-resource-traits.ejs
Documents changes in this database PR: https://github.com/5e-bits/5e-database/pull/380
Including changes to models.
Database run on local machine, ran tests according to docs.
No.
> Feature choice

- .github/workflows/ci.yml
- jest.config.integration.js
- package-lock.json
- package.json
- src/server.js
- src/start.js
- src/tests/integration/api/abilityScores.itest.js
- src/tests/integration/api/classes.itest.js
- src/tests/integration/api/conditions.itest.js
- src/tests/integration/api/damageTypes.itest.js
- src/tests/integration/api/equipment.itest.js
- src/tests/integration/api/equipmentCategories.itest.js
- src/tests/integration/api/features.itest.js
- src/tests/integration/api/languages.itest.js
- src/tests/integration/api/magicItems.itest.js
- src/tests/integration/api/magicSchools.itest.js
- src/tests/integration/api/monsters.itest.js
- src/tests/integration/api/proficiencies.itest.js
- src/tests/integration/api/races.itest.js
- src/tests/integration/api/ruleSections.itest.js
- src/tests/integration/api/rules.itest.js
- src/tests/integration/api/skills.itest.js
- src/tests/integration/api/spells.itest.js
- src/tests/integration/api/subclasses.itest.js
- src/tests/integration/api/subraces.itest.js
- src/tests/integration/api/traits.itest.js
- src/tests/integration/api/weaponProperties.itest.js
- src/tests/integration/server.itest.js
Takes the 10min integ test down to 2min. That was a wild ride.
CI
Nope
> Fix Integration Test Timeout

- src/views/partials/doc-resource-proficiencies.ejs
Updates the docs in line with the [proficiency reference changes](https://github.com/5e-bits/5e-database/pull/414#pullrequestreview-734543990).
n/a (documentation change)
[Yes](https://github.com/5e-bits/5e-database/issues/413)
> Update proficiency docs

- src/views/partials/head.ejs
Adds small Ukrainian flag banner to documentation website
> added ukraine support banner to docs site

- .eslintrc.json
- .gitignore
- package-lock.json
- package.json
- tools/copyAssets.ts
- tsconfig.json
I'm trying to break the big branch apart into small deployable pieces. This should make it a little more manageable for me.
CI
N/A
> Initial setup of TS

- README.md
fixes the url in the badge 
previewed
no
> readme: fix uptime and response time badges

- .github/workflows/ci.yml
> fix(release): Get tags to work

- .github/workflows/ci.yml
> fix(release): tag latest

- .github/workflows/ci.yml
- Dockerfile
- package.json
Updates the version of node used by docker because it wouldn't build locally on the old version.
I ran the server and made sure I could query the API.
No
n/a
> build: Update node version in Dockerfile

- package-lock.json
- package.json
- src/models/background/index.js
- src/models/background/types.d.ts
- src/models/class/index.js
- src/models/class/types.d.ts
- src/models/common/index.js
- src/models/common/types.d.ts
- src/models/feature/index.js
- src/models/feature/types.d.ts
- src/models/monster/index.js
- src/models/monster/types.d.ts
- src/models/race/index.js
- src/models/race/types.d.ts
- src/models/subrace/index.js
- src/models/subrace/types.d.ts
- src/models/trait/index.js
- src/models/trait/types.d.ts
- src/swagger/paths/backgrounds.yml
- src/swagger/paths/classes.yml
- src/swagger/paths/monsters.yml
- src/swagger/schemas/backgrounds.yml
- src/swagger/schemas/classes.yml
- src/swagger/schemas/combined.yml
- src/swagger/schemas/common.yml
- src/swagger/schemas/equipment.yml
- src/swagger/schemas/monsters.yml
- src/swagger/schemas/traits.yml
- src/swagger/swagger.yml
- src/tests/controllers/api/classController.test.js
This is the documentation update for the [choice reform PR](https://github.com/5e-bits/5e-database/pull/465).
I made sure `swagger-cli` could validate the changes and I ran the api locally to visually inspect the docs.
Yes, [the infamous choice structure reform issue](https://github.com/5e-bits/5e-database/issues/383).
The changes were entirely documentation changes.
> refactor(choice structure): Choice reform and accompanying docs

- package-lock.json
- package.json
- src/controllers/api/imageController.js
- src/models/monster/index.js
- src/models/monster/types.d.ts
- src/routes/api.ts
- src/routes/api/features.ts
- src/routes/api/images.ts
- src/routes/api/index.ts
- src/start.ts
- src/swagger/schemas/monsters.yml
- src/util/environmentVariables.ts
- src/util/index.ts
This serves an image based on the url.
Locally
N/A
Yes. However, I'm not sure I want to document `/api/images`
> feat: Allow serving of images from an S3 bucket

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
> build: Bump action versions

- package-lock.json
- src/middleware/apolloServer.ts
Turns on Introspection in Production. Normally, this is bad. But for our purposes as a public API, this is good since it lets new people construct test queries.
It's only in production kind of deal.
No
Nope
> feat: Turn on Apollo Introspection

- package.json
Fixes the currently broken integration tests. Looks like there's a current issue with `ts-node`.
This resolves #375 
Locally
> fix(build): Fix integration tests

- .github/dependabot.yml
Adds a dependabot file to handle normal package upgrades
I might regret this
Standard config
> build(packages): Create dependabot.yml

- docker-compose.yml
- package-lock.json
- package.json
- src/graphql/resolvers/common.ts
- src/graphql/resolvers/featureResolver.ts
- src/graphql/resolvers/spellResolver.ts
Does what it says on the tin
CI
> fix(node): Upgrade mongoose to v7 and lint

- src/tests/integration/server.itest.ts
Adjust test message to reflect reality
CI
No. Surfaced in Discord.
> fix(tests): Fix test description

- src/middleware/errorHandler.ts
- src/server.ts
Reduced verbosity of error handler middleware
Unit tests
Nope
Nope
> fix: reduce error middleware response verbosity

- package.json
Fixes error via https://github.com/orgs/community/discussions/116610
> build(integ): Update package.json to use new docker compose command

- package-lock.json
- package.json
- src/controllers/api/2014/imageController.ts
* Cleans up imageController and surface errors
* Update `@aws-sdk/client-s3`
Locally
N/A
> fix(images): Surface S3 errors and fix S3 package

- .github/workflows/ci.yml
Adjusts the CI to match the reality of using Node 20
CI
> ci: Bump node version from 18 to 20

- src/controllers/api/2014/imageController.ts
Cleans up the complaint from GH about usage of `next`
CI
> fix(lint): Remove use of unused `next`

- .github/workflows/ci.yml
- Updated Node.js and checkout actions to sha commit hashed versions to lower risk of supply chain compromise.
- Rearranged job dependencies to ensure proper execution order and prevent unnecessary execution
Watched the github action run
Nooope.
Nopppee.
> chore(ci): update github actions for improved dependency security

- docker-compose.yml
- package-lock.json
- package.json
- src/controllers/api/2014/classController.ts
- src/controllers/api/2014/magicItemController.ts
- src/controllers/api/2014/monsterController.ts
- src/controllers/api/2014/raceController.ts
- src/controllers/api/2014/ruleController.ts
- src/controllers/api/2014/ruleSectionController.ts
- src/controllers/api/2014/spellController.ts
- src/controllers/api/2014/subclassController.ts
- src/controllers/api/2014/subraceController.ts
- src/controllers/simpleController.ts
- src/schemas/schemas.ts
- src/tests/controllers/api/2014/classController.test.ts
- src/tests/controllers/api/2014/monsterController.test.ts
- src/tests/controllers/api/2014/subclassController.test.ts
* Adds the `zod` package
* Hooks up every controller that has param inputs to use `zod` for validation
Updates unit and integration tests to match.
Nope. Just fucking around and finding out.
> feat(zod): Swap API param validation to Zod

- .github/workflows/ci.yml
- .prettierrc
- docker-compose.yml
- eslint.config.js
- jest.config.integration.ts
- package-lock.json
- package.json
* Finally fixes integ tests to run in parallel
* Swaps @brittonhayes changes from `eslint` to `prettier`.
CI
> ci(integ): Speed up testing

- src/swagger/schemas/2014/backgrounds.yml
- src/swagger/schemas/2014/common.yml
This resolves #632 #633 #634 and #635 which were not able to be merged in previously
> docs(swaggger): Update swagger docs

- .releaserc.json
- package-lock.json
- package.json
* SR now updates the changelog
* SR now updates the package.json version
* SR now commits these changes but skips the CI when it does
We do it live
> feat(semver): Updates changelog and npm version on release

- src/controllers/api/2014/classController.ts
Previously, `/api/2014/classes/sorcerer/levels/1/spells` would give a list of Level 1 spells available to Sorcerer
Now that endpoint gives you the list of spells available at Sorcerer 1.
CI
Raised in Discord
I think I need to update the docs for this one.
> fix(class): showSpellsForClassAndLevel now gives the spells available at that class level

- eslint.config.js
- src/controllers/api/2014/classController.ts
- src/graphql/2014/types/startingEquipment/optionSet.ts
- src/server.ts
- src/tests/factories/2014/monster.factory.ts
- src/tests/integration/api/abilityScores.itest.ts
- src/tests/integration/api/classes.itest.ts
- src/tests/integration/api/conditions.itest.ts
- src/tests/integration/api/damageTypes.itest.ts
- src/tests/integration/api/equipment.itest.ts
- src/tests/integration/api/equipmentCategories.itest.ts
- src/tests/integration/api/feats.itest.ts
- src/tests/integration/api/features.itest.ts
- src/tests/integration/api/languages.itest.ts
- src/tests/integration/api/magicItems.itest.ts
- src/tests/integration/api/magicSchools.itest.ts
- src/tests/integration/api/monsters.itest.ts
- src/tests/integration/api/proficiencies.itest.ts
- src/tests/integration/api/races.itest.ts
- src/tests/integration/api/ruleSections.itest.ts
- src/tests/integration/api/rules.itest.ts
- src/tests/integration/api/skills.itest.ts
- src/tests/integration/api/spells.itest.ts
- src/tests/integration/api/subclasses.itest.ts
- src/tests/integration/api/subraces.itest.ts
- src/tests/integration/api/traits.itest.ts
- src/tests/integration/api/weaponProperties.itest.ts
- src/tests/support/db.ts
Handles linting for:
* `@typescript-eslint/no-unused-vars`
* `import-x/no-duplicates`
CI/CD
> fix(lint): Fix simple linting rules
