5e-bits/5e-srd-api

CHANGELOG.md, controllers/api/abilityScoreController.js, controllers/api/classController.js, controllers/api/conditionController.js, controllers/api/damageTypeController.js, controllers/api/equipmentCategoryController.js, controllers/api/equipmentController.js, controllers/api/languageController.js, controllers/api/magicSchoolController.js, controllers/api/monsterController.js, controllers/api/proficiencyController.js, controllers/api/raceController.js, controllers/api/skillController.js, controllers/api/spellController.js, controllers/api/subclassController.js, controllers/api/subraceController.js, controllers/api/traitController.js, controllers/api/utility.js, controllers/api/weaponPropertyController.js, package-lock.json, package.json, tests/integration/server.itest.js
=> Switch queries to be case insensitive

README.md, src/controllers/apiController.js, src/models/startingEquipment.js, src/tests/controllers/api/classController.test.js, src/tests/controllers/api/startingEquipmentController.test.js, src/views/partials/doc-resource-classes.ejs
This fixes the last remaining references to `/api/startingequipment` and converts them to `/api/starting-equipment`.
=> Last remaining `startingequipment` references

src/controllers/api/monsterController.js, src/models/monster.js, src/tests/integration/server.itest.js
Allows a user to query the monster list by challenge rating. Here are some examples:
`/monsters?challenge_rating=0`
`/monsters?challenge_rating=0.25,0.5`
`/monsters?challenge_rating=1,9,12`
Manually tested
This resolves issue #64.
=> Query monsters by challenge rating

src/models/level.js, src/tests/controllers/api/classController.test.js, src/tests/controllers/api/subclassController.test.js
Integrates changes to the database: indices for Level objects have been changed from integers to strings of the format `<(sub)class.index>-<level>`, e.g. `barbarian-1`, `berserker-3`.
**Important: [The PR that makes this modification to the database](https://github.com/bagelbits/5e-database/pull/245) MUST be merged before this one, to ensure minimal distruption.**
Tested with JEST, and in a local environment with the new data.
=> Switch to string indices for Level objects

src/models/abilityScore.js, src/models/class.js, src/models/condition.js, src/models/damageType.js, src/models/equipment.js, src/models/equipmentCategory.js, src/models/feature.js, src/models/language.js, src/models/level.js, src/models/magicSchool.js, src/models/monster.js, src/models/proficiency.js, src/models/race.js, src/models/skill.js, src/models/spell.js, src/models/spellcasting.js, src/models/startingEquipment.js, src/models/subclass.js, src/models/subrace.js, src/models/trait.js, src/models/weaponProperty.js
Makes sure `_id` no longer shows up in API requests. It changes on every DB deploy so is essentially useless.
Local testing
This resolves #80
=> Drop _id from any Mongo select

src/views/partials/doc-resource-ability-scores.ejs
make the documentation for ability scores accurate to the model
it wasn't?
issue #57 documentation-needs-helps
=>  removed _id from ability scores.ejs

docker-compose.yml, package-lock.json, package.json, src/controllers/api/monsterController.js, src/controllers/api/utility.js, src/start.js, src/tests/controllers/api/monsterController.test.js, src/tests/integration/server.itest.js, src/util.js
Implements the Redis cache that I've attached in Heroku.
This should be merged in tandem with https://github.com/bagelbits/5e-database/pull/252
Locally and with CI
No. I'm just tired of getting high response time emails for this endpoint and I want to see if this will help.
=> Add cacheing

src/controllers/api/spellController.js, src/start.js, src/tests/controllers/api/spellController.test.js, src/tests/integration/server.itest.js
This extends our caching to the `/api/spells` endpoint.
CI and local testing
No
=> Caching spells endpoint

src/views/partials/doc-resource-monsters.ejs
It adds documentation for the challenge_rating filter.
Manually tested
Yes #64
=> Added documentation for the challenge_rating filter

src/views/partials/doc-left-col.ejs, src/views/partials/doc-resource-ability-scores.ejs, src/views/partials/doc-resource-classes.ejs, src/views/partials/doc-resource-common-models.ejs, src/views/partials/doc-resource-equipment-categories.ejs, src/views/partials/doc-resource-equipment.ejs, src/views/partials/doc-resource-features.ejs, src/views/partials/doc-resource-lists.ejs, src/views/partials/doc-resource-proficiencies.ejs, src/views/partials/doc-resource-races.ejs, src/views/partials/doc-resource-skills.ejs, src/views/partials/doc-resource-spells.ejs, src/views/partials/doc-resource-subclasses.ejs, src/views/partials/doc-resource-subraces.ejs, src/views/partials/doc-resource-traits.ejs
- Changes the name of the NamedAPIResource structure to APIReference, to better reflect the purpose of the structure.
- Brings the docs up to date with [this database PR enforcing consistent structure for internal references (#249)](https://github.com/bagelbits/5e-database/pull/249):
- Updates example data to include *full* APIReference structures, by adding `index` attributes where they were lacking.
- Swaps ClassAPIResource structures in the data for URL strings
Note: The ClassAPIResource structure definition remains, as it is still used in the Spellcasting resource list generated by the API. In future, this structure can be fully removed when Spellcasting is merged into Class documents.
Locally
No issue on this repo, but resolves the request from @bagelbits on [issue #243 in the …
=> Update NamedAPIResource to APIReference in the Docs

src/views/partials/doc-resource-classes.ejs
Updates the documentation to include changes made by [this PR in the database repo](https://github.com/bagelbits/5e-database/pull/257), which adds a `spells` attribute to class documents, linking to the class spells Resource List endpoint in `/api/classes/{index}/spells`.
Locally
No, but complements [this PR in the database repo](https://github.com/bagelbits/5e-database/pull/257)
=> Add `spells` attribute to Classes docs

src/controllers/api/featureController.js, src/tests/integration/server.itest.js
This PR adds the `name` query parameter to the `/features` endpoint, so you can filter class features by their name.
Manually, as well as with the automated tests. I added tests to `server.itest.js` that test this endpoint with the parameter. Please let me know if more tests would be appropriate!
No, not that I know of.
=> Filter class features by the name query parameter

src/controllers/api/spellController.js, src/models/spell.js, src/tests/integration/server.itest.js, src/views/partials/doc-resource-spells.ejs
Exposes a `levels` query param for the spells endpoint.
CI and added tests.
This is part of #105
=> Spell level query

src/css/custom.css, src/views/partials/doc-left-col.ejs, src/views/partials/doc-resource-equipment.ejs
Cleans up the equipment docs so the links work and go to the right part. I've also added a gear and gear packs section as well.
`npm start` and poking around.
No
=> That cleans  things  up nicely

src/views/partials/doc-resource-equipment.ejs, src/views/partials/doc-resource-magic-items.ejs, src/views/partials/doc-resource-skills.ejs, src/views/partials/doc-resource-subclasses.ejs
The documentation incorrectly shows some properties as 'list ApiReference', when they are just ApiReferences. This fixes it
lgtm visually
No
=> Documentation: Remove 'list' from ApiReferences that are not lists

src/views/partials/doc-resource-ability-scores.ejs, src/views/partials/doc-resource-classes.ejs, src/views/partials/doc-resource-common-models.ejs, src/views/partials/doc-resource-conditions.ejs, src/views/partials/doc-resource-damage-types.ejs, src/views/partials/doc-resource-equipment-categories.ejs, src/views/partials/doc-resource-equipment.ejs, src/views/partials/doc-resource-features.ejs, src/views/partials/doc-resource-languages.ejs, src/views/partials/doc-resource-lists.ejs, src/views/partials/doc-resource-magic-items.ejs, src/views/partials/doc-resource-magic-schools.ejs, src/views/partials/doc-resource-monsters.ejs, src/views/partials/doc-resource-proficiencies.ejs, src/views/partials/doc-resource-races.ejs, src/views/partials/doc-resource-rule-sections.ejs, src/views/partials/doc-resource-rules.ejs, src/views/partials/doc-resource-skills.ejs, src/views/partials/doc-resource-spellcasting.ejs, src/views/partials/doc-resource-spells.ejs, src/views/partials/doc-resource-starting-equipment.ejs, src/views/partials/doc-resource-subclasses.ejs, src/views/partials/doc-resource-subraces.ejs, src/views/partials/doc-resource-traits.ejs, src/views/partials/doc-resource-weapon-properties.ejs
- Fixes a few small typos in the descriptions for `Ability Score` and `Skill`
- Adds missing periods to all field descriptions
- Some descriptions ended with periods, some didn't, this standardizes it so they all end in periods
Tested locally with these steps:
- Run `docker-compose up --build`
- Spot checked `http://localhost:3000/docs`
No
=> ecs: small documentation improvements

src/views/partials/doc-resource-traits.ejs, src/views/partials/doc-resource-weapon-properties.ejs
- update documentation for `desc` field on `Trait` to be list of string rather than array
- update documentation for `desc` field on `WeaponProperty` to be list of string rather than array
- spot checked localhost
no
=> ecs: small documentation improvements (2)

Dockerfile
Converts Dockerfile to use the node-14.15 image.
`docker build .` and CI
No
=> Upgrade node docker image

src/models/abilityScore.js, src/models/condition.js, src/models/damageType.js, src/models/language.js, src/models/magicSchool.js, src/models/rule.js, src/models/ruleSection.js, src/models/trait.js, src/models/weaponProperty.js
Adds all fields to the Mongoose schema for:
Locally and CI
Working to resolve part of #153
=> Update Some Mongoose Schemas

src/models/feature.js, src/models/race.js, src/models/spell.js, src/models/subclass.js, src/models/subrace.js
Adds all fields to the Mongoose schema for:
Locally and CI
Working to resolve part of #153
=> Some more mongoose

src/models/abilityScore.js, src/models/equipmentCategory.js, src/models/feature.js, src/models/magicItem.js, src/models/monster.js, src/models/proficiency.js, src/models/race.js, src/models/rule.js, src/models/skill.js, src/models/spell.js, src/models/subclass.js, src/models/subrace.js, src/models/trait.js
It was pointed out that sub schemas are adding the `_id` field. So this removes that.
CI and local
No. Mentioned in #help in discord.
=> Remove _id from struct

src/models/abilityScore.js, src/models/class.js, src/models/common.js, src/models/equipment.js, src/models/equipmentCategory.js, src/models/feature.js, src/models/level.js, src/models/magicItem.js, src/models/monster.js, src/models/proficiency.js, src/models/race.js, src/models/rule.js, src/models/skill.js, src/models/spell.js, src/models/startingEquipment.js, src/models/subclass.js, src/models/subrace.js, src/models/trait.js
Renames `NamedAPIResource ` to `APIReference`
CI
No
=> Rename to APIReference

src/controllers/api/spellController.js
Fixes a security vulnerability in spells that allowed for regex injection
CI
Security issue
=> Escape regex in spells

src/views/partials/doc-resource-common-models.ejs
- Fix a typo in the anchor tag
- localhost
current bad behavior in production:
fixed behavior testing locally:
- no
=> ecs: fix ability scores anchor tag

package-lock.json, package.json, src/middleware/apolloServer.js
Adds in Apollo's own in-memory caching for GraphQL. It is based on [Apollo's in-memory cache instructions](https://www.apollographql.com/docs/apollo-server/performance/caching/#in-memory-cache-setup) and [their setup for default Max Age](https://www.apollographql.com/docs/apollo-server/performance/caching/#default-maxage).
CI and locally. Drops response time by an order of magnitude.
Nope
=> Add Apollo GraphQL caching

src/graphql/schema.js
Generates operators for all fields. Fields include:
* Available logic operators: AND, OR
* Available field operators: gt, gte, lt, lte, ne, in, nin, regex, exists
CI
Nope. But there should be.
=> Allow GraphQL Filter operators for all fields

src/views/partials/doc-resource-spells.ejs
Add's the name attribute to spell's documentation table
It wasn't.
No.
=> Spell name added to spell doc

src/controllers/api/classController.js, src/models/class.js, src/routes/api/classes.js, src/tests/controllers/api/classController.test.js, src/tests/integration/api/classes.itest.js, src/views/partials/doc-resource-classes.ejs
Technically, the API was supporting Multiclassing fields. However, this adds a multi-class specific endpoint and adds it to GraphQL. It also adds 
Tested GraphQL locally and added in unit and integration tests.
None. Raised in Discord.
=> Add full multi-class support

src/controllers/apiController.js
Adds feats to the list of endpoints that a request to the base url of the API shows
I added the url for feats and made sure it showed up when hitting the base url with Postman
No
=> Add feats to response from base endpoint that shows available endpoints

src/models/level.js, src/views/partials/doc-resource-classes.ejs, src/views/partials/doc-resource-subclasses.ejs
Removes features choices to mirror https://github.com/5e-bits/5e-database/pull/400
CI
https://github.com/5e-bits/5e-database/issues/241
=> Removes feature choices

Dockerfile, heroku.yml
Heroku falls over and due to memory issues if we try to build on startup, which frankly makes sense when I think about it. Instead, build should be part of the Dockerfile.
Deployed to heroku from branch.
N/A Just random thing.
=> Bagelbits.docker heroku fix

tools/copyAssets.ts
I forgot to copy the public folder which stores the assets for favicon.
Locally.
Not yet but I'm  sure someone would notice
=> Forgot to copy public folder

src/models/proficiency.js, src/views/partials/doc-resource-proficiencies.ejs
`reference` not `references`
N/A
N/A
=> Adjust proficiency

src/models/background/index.js, src/models/class/index.js, src/models/common/index.js, src/models/equipment/index.js, src/models/feat/index.js, src/models/feature/index.js, src/models/level/index.js, src/models/monster/index.js, src/models/proficiency/index.js, src/models/race/index.js, src/models/spell/index.js, src/models/subclass/index.js, src/models/subrace/index.js, src/models/trait/index.js
Removes `_id` from sub documents. I think that got reverted somehow so I'm putting it back.
CI
No
=> Remove _id from sub documents

src/views/partials/doc-resource-equipment-categories.ejs, src/views/partials/doc-resource-equipment.ejs, src/views/partials/doc-resource-proficiencies.ejs
Two tiny tweaks to documentation to bring the docs inline with the actual response.
Viewed docs page on localhost, and verified the new descriptions match the shape of what's actually returned from the endpoint.
no
=> ecshreve: two small tweaks to docs

docker-compose.yml, src/server.ts, src/util/RedisClient.ts, src/util/environmentVariables.ts
The initial symptom  was CORS which I fixed. But the actual issue, is that Heroku updated the Redis instance and the URL but I don't listen to it when the server comes up. So I've switched back to using `REDIS_URL`.
CI and also deployed.
Raised in  Discord
=> Put back CORS and fix Redis configuration

.github/workflows/ci.yml, docker-compose.yml
Switches us from dockerhub to github container store in the `docker-compose.yml`. Thanks to the work that @peshka did.
Running the CI
Nope.
I don't... think so?
=> Switch to github container

src/controllers/api/classController.js, src/swagger/README.md, src/swagger/parameters/path/classes.yml, src/swagger/paths/ability-scores.yml, src/swagger/paths/alignments.yml, src/swagger/paths/backgrounds.yml, src/swagger/paths/classes.yml, src/swagger/paths/languages.yml, src/swagger/paths/proficiencies.yml, src/swagger/paths/skills.yml, src/swagger/schemas/alignments.yml, src/swagger/schemas/backgrounds.yml, src/swagger/schemas/classes.yml, src/swagger/schemas/combined.yml, src/swagger/schemas/common.yml, src/swagger/schemas/equipment.yml, src/swagger/schemas/language.yml, src/swagger/swagger.yml
- Small tweaks to  schemas to align them with actual behavior. 
- Also makes a change to one controller to properly check and return a `404` if a `classLevel` doesn't have a `spellcasting` attribute.
- localhost
- generated postman test collection from the `openapi.json`  and used it and validated that changes resolved the test failures related to the response body not matching the schema in the documentation
no
no
=> ecshreve: [openapi] - small tweaks to bring docs in line with prod

src/swagger/parameters/query/monsters.yml, src/swagger/parameters/query/spells.yml, src/swagger/paths/subclasses.yml, src/swagger/schemas/classes.yml, src/swagger/schemas/monsters.yml, src/swagger/schemas/rules.yml, src/swagger/schemas/subrace.yml
Worked with a generated postman collection locally to verify the response schemas in the docs matched the schema of what was actually returned from the api. This process uncovered a number of small inconsistencies, this PR fixes those.
localhost
no
these are docs
=> ecshreve: [docs] - last few changes to bring docs schema in line with reality

src/models/level/index.js, src/swagger/paths/classes.yml
The creating_spell_slots field is an array of subdocuments, and
in mongoose arrays implicitly have a default value of []. This was
causing this field to be included in the response for every resource
from this endpoint regardless of class.
Explicitly setting default: undefined fixes this.
see the "Arrays" section under "SchemaType Options": https://mongoosejs.com/docs/schematypes.html#schematype-options
localhost
no
fixing the documentation for this endpoint was how i found this bug :)
=> ecshreve: [bug] - fix schema field definition for class level

src/models/magicItem/index.js, src/models/magicItem/types.d.ts, src/swagger/paths/magic-items.yml, src/swagger/schemas/equipment.yml
adds rarity and variants to magic items
Loaded up data from 5e-bits/5e-database#455 and verified documentation from OpenAPI and GraphQL looked correct
5e-bits/5e-database#455
Yes, magic items
=> feat(magic-item): update schema for magic items

.dockerignore, package.json, src/controllers/api/classController.js, src/swagger/parameters/combined.yml, src/swagger/parameters/query/classes.yml, src/swagger/paths/classes.yml, src/tests/controllers/api/classController.test.js, src/tests/integration/api/classes.itest.ts
Locally
This has been raised a few times in Discord and I'm finally fixing it.
Yup!
=> feat(levels):  Add  `subclass` query and drop subclasses from normal request

src/swagger/paths/classes.yml
I used the wrong parameter in the  docs.
I haven't figured out how to test this correctly yet.
Not yet.
Yes but well... you get it.
=> fix(docs): Wrong parameter

src/models/class/index.js, src/models/monster/index.js
This came up during #248. We sometimes get empty arrays in the response that don't actually exist in the data. I'm  cleaning up some of the remaining ones. Thanks to @ecshreve for pointing out how to do this.
Locally. After deleting all other docker containers and rebuilding  from scratch.
Not exactly. Just a running tally.
Nope.
=> fix(mongoose): Marking some more fields defaults as `undefined`

.github/workflows/ci.yml
Previously we were tagging our containers as `main` instead of the version
Built on a separate repo
None yet
Nope
=> fix(release): Tags should use version now

src/tests/integration/api/magicItems.itest.ts
And this is why I should cut PRs for things that can be tested.
Ran locally.
No.
Nope
=> fix(integration tests): Select better test magic item

src/controllers/apiController.js, src/tests/integration/server.itest.ts
I forgot to clear out this from the automatic `/api` endpoint.
Adjusted tests accordingly.
This resolves #304 
None.
=> fix(api): levels should not show up in api root

src/graphql/resolvers/traitResolver.js, src/graphql/typeDefs.graphql, src/models/trait/index.js, src/swagger/schemas/traits.yml
Adds language_options to trait mongoose schema. See the [other PR](https://github.com/5e-bits/5e-database/pull/494).
Ran the API locally
n/a
n/a
=> feat(trait language options): Add language options to trait

src/middleware/apolloServer.ts
Increases the max depth that can be used. Some valid queries were failing because of the depth limit.
I ran the GraphQL API locally and queried it.
no
n/a
=> fix: Increase GraphQL API's max query depth

src/graphql/resolvers/common.js, src/graphql/resolvers/spellResolver.js, src/graphql/resolvers/traitResolver.js, src/graphql/typeDefs.graphql, src/models/common/index.js, src/models/common/types.d.ts, src/models/spell/index.js, src/models/spell/types.d.ts, src/models/trait/index.js, src/models/trait/types.d.ts, src/swagger/schemas/combined.yml, src/swagger/schemas/common.yml, src/swagger/schemas/spell.yml, src/swagger/schemas/traits.yml
Adds size and shape of dragonborn's breath weapon since it wasn't in the API already
I ran the API locally and verified I could query the new property
n/a
Yes. I updated the schema in swagger
=> feat: add size and shape to breath weapon

src/controllers/api/classController.js, src/controllers/api/magicItemController.js, src/controllers/api/monsterController.js, src/controllers/api/raceController.js, src/controllers/api/ruleController.js, src/controllers/api/ruleSectionController.js, src/controllers/api/spellController.js, src/controllers/api/subclassController.js, src/controllers/api/subraceController.js, src/controllers/simpleController.js
The server gets brought down sometimes due to bad queries. We should wrap everything in the try/catch block so it doesn't crash.
CI
No. Just realized it from the outage today.
No.
=> fix: Malformed queries should not break the server

src/graphql/resolvers/classResolver.js
As the title says. If you run the following query: 
```graphql
query Class {
class(index: "cleric") {
starting_equipment_options {
choose
desc
from {
... on EquipmentCategoryOptionSet {
equipment_category {
index
name
}
}
... on EquipmentOptionSet {
options {
... on CountedReferenceOption {
count
of {
index
name
... on Pack {
contents {
quantity
item {
index
name
}
}
}
}
prerequisites {
type
proficiency {
name
type
index
}
}
}
... on EquipmentCategoryChoiceOption {
choice {
choose
from {
equipment_category {
index
name
}
}
}
}
... on EquipmentMultipleOption {
items {
... on CountedReferenceOption {
count
of {
index
name
... on Pack {
contents {
quantity
item {
index
name
}
}
}
}
prerequisites {
type
proficiency {
index
name
type
}
}
}
... on EquipmentCategoryChoiceOption {
choice {
choose …
```
=> fix: Fix issue with fetching cleric starting equipment options with prerequisites

src/graphql/typeDefs.graphql
This PR fixes the issue that when quering the API using GraphQL for Magic Items and there is a magic Item with Common Rarity, the API return a 500 response because there no "Common" rarity listed on the enum for the GrapQL.
Using the Apollo sandbox explorer perform the following query with the following Variables:
Query:
```graphql
query MagicItemsQuery($equipmentCategory: StringFilter, $order: MagicItemOrder) {
magicItems(equipment_category: $equipmentCategory, order: $order) {
index
name
desc
rarity
equipment_category {
index
name
}
}
}
```
Variables
```json
{
"equipmentCategory": null,
"order": {
"by": "EQUIPMENT_CATEGORY",
"direction": "ASCENDING",
"then_by": {
"by": "NAME",
"direction": "ASCENDING",
}
}
}
```
This resolves issue #331
\<It's not clear if I don't update this text with …
=> fix: add common rarity to magic items rarity enum

src/graphql/typeDefs.graphql
This PR fixes the issue that when quering the API using GraphQL for Magic Items and there is a magic Item with Common Rarity, the API return a 500 response because there no "ARTIFACT" rarity listed on the enum for the GraphQL.
Using the Apollo sandbox explorer perform the following query with the following Variables:
Query:
```graphql
query MagicItemsQuery($equipmentCategory: StringFilter, $order: MagicItemOrder) {
magicItems(equipment_category: $equipmentCategory, order: $order) {
index
name
desc
rarity
equipment_category {
index
name
}
}
}
```
#331 (ish)
N/A
=> fix: add ARTIFACT rarity to magic items rarity enum

src/graphql/typeDefs.graphql, src/models/monster/index.js, src/models/monster/types.d.ts, src/swagger/paths/monsters.yml, src/swagger/schemas/monsters.yml
I saw @Stuart-Yee [added a new field to monsters for hit points rolls.](https://github.com/5e-bits/5e-database/pull/500) I updated the GraphQL schema to have the new property.
I honestly can't test this unless I was able to use the database changes in Stuart's branch, but the change is simply adding a primitive type property to a type, so there's not any logic to test.
No.
Yes
=> fix: (src/5e-SRD-Monsters.json): added modifiers to hit dice

src/graphql/typeDefs.graphql, src/models/monster/types.d.ts
Adds monster image url to GraphQL API
n/a
n/a
n/a
=> fix: Add monster image to GraphQL API

src/controllers/api/monsterController.js, src/tests/integration/api/monsters.itest.ts
Allows the API to handle CR queries like `challenge_rating=1,2`. It won't allow `challenge_rating=[1,2]` to crash the API as a malformed query.
Locally
Nope
No
=> fix: CR query shouldn't break with lists

src/graphql/resolvers/monsterResolver.ts, src/graphql/resolvers/queryResolver.ts, src/graphql/typeDefs.graphql, src/models/common/index.ts, src/models/feature/index.ts, src/models/monster/index.ts, src/models/monster/types.d.ts, src/swagger/paths/monsters.yml, src/swagger/schemas/monsters.yml
BREAKING CHANGE: Changes the shape of armor_class in monsters
Changes the shape of armor_class in monsters from a number to:
```typescript
type ArmorClass = (ArmorClassDex | ArmorClassNatural | ArmorClassArmor | ArmorClassSpell | ArmorClassCondition)[];
type ArmorClassDex = {
type: "dex";
value: number;
desc?: string;
};
type ArmorClassNatural = {
type: "natural";
value: number;
desc?: string;
}
type ArmorClassArmor = {
type: "armor";
value: number;
armor?: APIReference[]; // Equipment
desc?: string;
}
type ArmorClassSpell = {
type: "spell";
value: number;
spell: APIReference; // Spell
desc?: string;
}
type ArmorClassCondition = {
type: "condition";
value: number;
condition: APIReference; // Condition
desc?: string;
}
```
CI
<https://github.com/5e-bits/5e-database/issues/280>
Heck yeah!
=> feat: Add Monster Armor Types

src/swagger/schemas/combined.yml, src/swagger/schemas/monsters-common.yml, src/swagger/schemas/monsters.yml
Move swagger schema model definitions for monster related things to their own file. Import those definitions in the combined file. Change all references to point to the combined file.
localhost and compared generated openapi specs with `npm run bundle-swagger`. The new spec does not contain the offending lines like `#/paths/~1api~1monsters~1%7Bindex%7D/get/responses/200/content/application~1json/schema/allOf/3/properties/actions/items/properties/damage/items'` anymore.
should address https://github.com/5e-bits/5e-srd-api/issues/352
this updates documentation
=> fix: remove circular references from monster swagger docs

src/graphql/typeDefs.graphql
expose `alignment` field on the `Monster` type
localhost
https://github.com/5e-bits/5e-srd-api/issues/358
no, docs were already correct
=> fix(gql): add alignment field to monster type

src/swagger/parameters/path/rule-sections.yml
SRD 5.1 added magic item attunement, wearing/wielding, and activation rules that were omitted from SRD 5.0. This adds them as rule-sections.
5e-bits/5e-database#527
:rotating_light:  After confirming that I can build 5e-database and view the changes, I tried following the README instructions to build the API and database locally:
```diff
services:
db:
-    image: ghcr.io/5e-bits/5e-database:latest
-    # build: ../5e-database
+    # image: ghcr.io/5e-bits/5e-database:latest
+    build: ../5e-database
ports:
- "27017:27017"
```
```
sudo docker-compose up --build
```
The branches of both repos are set to the corresponding changes. There are no errors, but the changes don't appear in the local API.
No.
Yes; this is only a documentation change.
=> feat: Add magic item attunement, wielding, and activation rules

README.md, package-lock.json, package.json, src/controllers/api/imageController.ts, src/start.ts, src/util/awsS3Client.ts, src/util/environmentVariables.ts, src/util/index.ts
- update aws-sdk to v3 per [documentation](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html) linked in a build warning about deprecating v2
- the main item that affected us is related to configuration: https://github.com/aws/aws-sdk-js-v3/tree/main#configuration
- to facilitate the above, this PR reworks how some aws config variables are set and where the s3 client is created
- [localstack](https://docs.localstack.cloud/getting-started/) on localhost
- for localstack setup i more or less followed this guide: https://docs.localstack.cloud/user-guide/aws/s3/
```
- install localstack
- install awscli
- install awscli-local
- create bucket via awslocal 
> awslocal s3api create-bucket --bucket sample-bucket   
- upload image to bucket
```
--
- no, i found …
=> chore: update aws sdk config to v3

README.md, docker-compose.yml, package-lock.json, package.json, src/graphql/resolvers/scalars/floatFilterResolver.ts, src/graphql/resolvers/scalars/intFilterResolver.ts, src/middleware/apolloServer.ts, src/server.ts
Bumps our `graphql` package up a major version as well as upgrades us to Apollo server 4. 
Local testing and CI
N/A
Nope
=> chore(apollo): Apollo 4 upgrade

src/graphql/typeDefs.graphql, src/swagger/paths/monsters.yml, src/swagger/schemas/monsters.yml
Updates the swagger and graphql schemas for the new `proficiency_bonus` field on Monster documents.
Built the image and tested locally
Resolves 5e-database#550, alongside [database changes](https://github.com/5e-bits/5e-database/pull/551).
Docs generated from swagger will be updated.
=> feat: add proficiency_bonus field to Monsters

src/views/partials/navbar.ejs
Links to our new docs site.
Similar to our other links and I tested the URL
Not really
Buddy you have no idea
=> feat(docs): Link to new docs

src/middleware/errorHandler.ts, src/server.ts
- Adds an error handler middleware to the express server so errors are neatly caught and responded to in JSON format
- Bumps the rate limit to something a little more reasonable like 1000req/sec per IP instead of the 10,000 it was before 
Ran npm run test:unit to verify all the handlers still worked
Nope
Nope
=> feat: added error handler middleware and rate limiting improvements

src/server.ts
Reduce rate limit to 50 requests per second per IP address.
Unit tests were ran
Nope
Not yet. We should probably add a tutorial showing how to handle rate limiting in our documentation.
=> fix: reduce rate limit to 50 requests per second per IP

package-lock.json, src/graphql/typeDefs.graphql, src/models/magicItem/index.ts, src/models/magicItem/types.d.ts, src/swagger/schemas/equipment.yml
* Adds `image` to API magic items endpoint
* Adds `image` to GraphQL query for magic items
* Adds `image` to swagger docs for magic items
Locally
Yes
=> feat(magic-items): Support images for magic items

README.md
- fix build status badge 
- update documentation section to be accurate
- fix link to point at correct url for db repo
- localhost
nope
this is docs
=> fix: update links and paths in readme

eslint.config.js, jest.config.integration.ts, jest.config.ts, jest.config.unit.ts, package-lock.json, package.json, src/controllers/api/imageController.ts, src/graphql/resolvers/levelResolver.ts, src/js/code.js, src/middleware/errorHandler.ts
- refactors eslint config file to align more closely with the [eslint config in the db repo](https://github.com/5e-bits/5e-database/blob/main/eslint.config.mjs)
- most notably removes the usage of a 3rd party helper function to build the config, using standard eslint config file format instead
- also updates the jest configuration files to use typescript types from `@jest/types`
- ran `npm run lint` locally
no
no
=> refactor: small updates to eslint config

src/swagger/api-spec/openapi.json, src/swagger/api-spec/openapi.yml, src/swagger/paths/classes.yml
This is the only place where we do return the level along with the spell apireference.
=> fix: correct class spell list example

src/js/code.js, tools/copyAssets.ts, tsconfig.json
- include the /src/js directory so it gets picked up at buildtime
- use suggested inline ignore comment
- also update copyAssets to copy openapi spec to correct directory
localhost
- also built the docker image and ran it locally to double check
- I broke this last week making some eslint / ts configuration changes
#622 
n/a
=> fix: include code.js in tsconfig

package.json, tools/copyAssets.ts
Migrates the `copyAssets.ts` to an inline command in `package.json`
`docker-compose up --build`
No.
No.
=> fix(copyAssets): Remove copyAssets need

README.md, src/controllers/api/2014/classController.ts, src/controllers/api/2014/raceController.ts, src/controllers/api/2014/subclassController.ts, src/controllers/api/2014/subraceController.ts, src/public/index.html, src/util/prewarmCache.ts
Updates various paths throughout the 2014 controllers, cache prewarming, the README and the website, to use the new versioned `/api/2014` endpoint.
Visiting the affected endpoints in a local docker build.
No
N/A
=> fix: :bug: update some missed unversioned /api paths

src/graphql/2014/resolvers/featureResolver.ts, src/graphql/2014/typeDefs.graphql, src/models/2014/feature/index.ts, src/models/2014/feature/types.d.ts, src/swagger/schemas/2014/features.yml
- Added new fields to Feature types and schemas for Rangers' Natural Explorer and Favored Enemy choices
- Updated Mongoose schema, TypeScript types, OpenAPI schema, and GraphQL schema/resolvers
- Supports PRs #794 and #795 from the 5e-bits/5e-database repository
=> feat: add terrain_type_options and enemy_type_options to feature schema

src/models/2014/abilityScore.ts, src/models/2014/alignment.ts, src/models/2014/background.ts, src/models/2014/class.ts, src/models/2014/collection.ts, src/models/2014/condition.ts, src/models/2014/damageType.ts, src/models/2014/equipment.ts, src/models/2014/equipmentCategory.ts, src/models/2014/feat.ts, src/models/2014/feature.ts, src/models/2014/language.ts, src/models/2014/level.ts, src/models/2014/magicItem.ts, src/models/2014/magicSchool.ts, src/models/2014/monster.ts, src/models/2014/proficiency.ts, src/models/2014/race.ts, src/models/2014/rule.ts, src/models/2014/ruleSection.ts, src/models/2014/skill.ts, src/models/2014/spell.ts, src/models/2014/subclass.ts, src/models/2014/subrace.ts, src/models/2014/trait.ts, src/models/2014/weaponProperty.ts, src/tests/util/data.test.ts, src/util/data.ts, src/util/index.ts, src/util/modelOptions.ts
* Updates model files to once again no longer show `_id` of `id` fields
* This is done by adding a new decorator called `srdModelOptions` which both scrubs the data and also sets the collection name.
* Removes `ClassAPIResource` which is no longer used
By spinning up the server and hitting some of the API endpoints
[Raised in #help in discord](https://discord.com/channels/656547667601653787/664902912014680068/1360462933288816832)
=> fix(models): Remove _id and id fields from response

.github/PULL_REQUEST_TEMPLATE.md
Swaps PR template from image to text so people actually add images.
In other repos.
=> docs(PR): Swap image link to text so people actually add images

src/models/2014/monster.ts, src/models/2014/spell.ts, src/models/2014/trait.ts
Quiets all the Mixed warnings from Typegoose that have been showing up during startup and testing.
I ran the integration tests and spun up the server
=> fix(models): No more Mixed warnings from Typegoose

src/models/2014/equipment.ts, src/models/2014/magicItem.ts, src/swagger/schemas/2014/equipment.yml, src/tests/factories/2014/equipment.factory.ts
Exposes equipment image to API
CI
Yes
=> feat(equipment): Add image to 2014 equipment model

src/graphql/2014/resolvers/subraceResolver.ts
Updates `SubraceResolver.language_options` to correctly resolve the options array. Previously, the options objects were replaced with the resolved `item`, replacing only the value of the `item` attribute.
Locally, ad-hoc & ran unit tests.
No.
N/A
=> fix: :bug: Resolve full `Option` objects in `subrace.language_options` resolver

src/models/2014/alignment.ts, src/models/2014/language.ts, src/models/2014/magicSchool.ts, src/models/2014/subrace.ts, src/tests/factories/2014/alignment.factory.ts, src/tests/factories/2014/language.factory.ts, src/tests/factories/2014/magicSchool.factory.ts, src/tests/factories/2014/subrace.factory.ts
When I migrated to Typegoose, I missed typed a few fields to be `String[]`. This fixes them to match the reality of the data.
CI
=> fix(desc): Fix models to match data reality for desc

src/controllers/api/2014/classController.ts, src/swagger/paths/2014/classes.yml, src/tests/controllers/api/2014/classController.test.ts
This PR introduces an optional level query parameter to the /api/2014/classes/{index}/spells endpoint, allowing clients to filter spells by one or more spell levels.
* `classController.ts`: Updated showSpellsForClass to parse and apply the level filter using SpellIndexQuerySchema for validation.
* `classController.test.ts`: Added comprehensive unit tests for the new level filtering capabilities, including various valid and invalid input scenarios.
Updated relevant unit tests
[Raised in Discord](https://discord.com/channels/656547667601653787/907534016440315934/1378083564737925344)
Updated the swagger doc as well.
=> feat(class): Add `level` query for class spells for filtering spell level

src/graphql/2014/resolvers/index.ts, src/graphql/2014/resolvers/spell/resolver.ts
Fixes this query:
```
query SpellQuery {
spells {
dc {
desc
dc_success
dc_type {
full_name
}
}
}
}
```
`dc_type` was not resolving to `AbilityScore` and was just returning the `APIReference`.
Locally running the graphql sandbox
Nope. Raised in `#help` in the Discord
Nope
=> fix(graphql): Spell DC now resolves to Ability Score
